config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :departments
  resources :companies, only: [:show,:edit, :update]
  resources :users
	root 'sessions#new'
    get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/presence.rb
class Presence < ApplicationRecord
	belongs_to :user
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.all
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)
    
    respond_to do |format|
      if @presence.save
        format.html { redirect_to @presence.user, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence.user, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    #if Presence.exists?
      respond_to do |format|
      format.html { redirect_to @presence.user, notice: 'Presence was successfully destroyed.' }      
      end      
    #else
     # respond_to do |format|
     # format.html { redirect_to users_path, notice: 'Presence was successfully destroyed.' }      
    #  end      
    #end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:date, :hour_in, :user_id, :start_hour)
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_with(model: presence, local: true) do |form| %>  
<%= render 'shared/errors', obj: @presence %>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, :value => Date.today, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :hour_in %>
    <%= form.time_select :hour_in,  { class: 'form-control' }  %>
  </div>

  <% if params[:action] == "new" %>
    <%= form.hidden_field :user_id, :value => params[:user_id].html_safe %>
  <% else %>
    <%= form.hidden_field :user_id %>
  <% end %> 

  <div class="form-group">
    <%= form.button(@presence.new_record? ? '<i class="fas fa-user-plus"></i> Create presence'.html_safe : '<i class="fas fa-paper-plane"></i> Update presence'.html_safe, class: "btn btn-outline-success btn-sm btn-block")  %>
  </div>
<% end %>

app/views/presences/edit.html.erb
<h1 align="center">Edit Presence</h1>

<%= render 'form', presence: @presence %>

<div class="row">
	<div class="col-md-12">
		<%= link_to '<i class="fas fa-users"></i> Back to user'.html_safe, @presence.user, 
					class: "btn btn-outline-secondary btn-sm btn-block" %>
	</div>
</div>

app/views/presences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presences</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hour in</th>
      <th>User</th>
      <th>Start hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presences.each do |presence| %>
      <tr>
        <td><%= presence.date %></td>
        <td><%= presence.hour_in %></td>
        <td><%= presence.user_id %></td>
        <td><%= presence.start_hour %></td>
        <td><%= link_to 'Show', presence %></td>
        <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
        <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presence', new_presence_path %>

app/views/presences/new.html.erb
<h1>New Presence</h1>

<%= render 'form', presence: @presence %>

<div class="row">
	<div class="col-md-12">
		<%= link_to '<i class="fas fa-users"></i> Back to user'.html_safe, user_path(:id => params[:user_id]), 
					class: "btn btn-outline-secondary btn-sm btn-block" %>
	</div>
</div>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @presence.date %>
</p>

<p>
  <strong>Hour in:</strong>
  <%= @presence.hour_in %>
</p>

<p>
  <strong>User:</strong>
  <%= @presence.user_id %>
</p>

<p>
  <strong>Start hour:</strong>
  <%= @presence.start_hour %>
</p>

<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>