config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :departments
  resources :companies, only: [:show,:edit, :update]
  resources :users
	root 'sessions#new'
    get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :company
	belongs_to :department
	has_many :presences

	before_save { self.email = email.downcase }

	validates :first_name, :last_name, :dob, :start_date, presence: true
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
			  uniqueness: {case_sensitive: false}, 
	          length: { maximum: 105},
	          format: { with: VALID_EMAIL_REGEX }

	has_secure_password

	def self.search(search)
	    users = all
	  if search
	    where('first_name ILIKE ? OR email ILIKE ?',"%#{search}%", "%#{search}%")
	  else
	    all
	  end
	end

	def full_name
      "#{first_name} #{middle_name}#{" " if middle_name.present?}#{last_name}".titleize   
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  skip_before_action :require_admin, only: [:show]

  def index   
    @users = User.all.order(:last_name)
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save     
      flash[:success] = "User added #{@user.full_name}"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)      
      flash[:success] = "Profile of #{@user.full_name} was  updated"
      redirect_to user_path(@user)
    else
      render 'new'
    end    
  end

  def show
    
  end

  def edit
    
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted"
      redirect_to users_path
    
  end

  private  

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    # List of common params
      list_params_allowed =[:first_name, :middle_name, :last_name, :email, :password, 
        :password_confirmation, :company_id, :department_id, :dob, :address, :start_date, 
        :end_date, :position, :holiday, :sick_days, :eveniment, :holiday_taken, :sick_days_taken, 
        :eveniment_taken, :start_hour]
        # Add the params only for admin
      list_params_allowed << :admin if current_user.admin?
    params.require(:user).permit(list_params_allowed)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<br>
<%= form_with(model: user, local: true) do |form| %>  
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :middle_name %>
      <%= form.text_field :middle_name, id: :user_middle_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, id: :user_last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :dob %>
      <%= form.date_field :dob, id: :user_dob, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, id: :user_address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_date %>
      <%= form.date_field :start_date, id: :user_start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :end_date %>
      <%= form.date_field :end_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :position %>
      <%= form.text_field :position, id: :position, class: "form-control" %>
    </div>

    

    <div class="form-group">
      <%= form.label :start_hour %>
      <%= form.time_select :start_hour, as: :time, class: "form-control" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :holiday %>
          <%= form.number_field :holiday, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :holiday_taken %>
          <%= form.number_field :holiday_taken, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :sick_days %>
          <%= form.number_field :sick_days, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :sick_days_taken %>
          <%= form.number_field :sick_days_taken, {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :eveniment %>
          <%= form.number_field :eveniment, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :eveniment_taken %>
          <%= form.number_field :eveniment_taken, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :company %>
      <%= form.collection_select :company_id, Company.all, :id, :name, {prompt: "Select a Company"}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :department %>
      <%= form.collection_select :department_id, Department.all, :id, :name, {prompt: "Select a Company"}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password_digest, class: "form-control" %>
    </div>

    <% if @user.new_record? %>
      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: "form-control" %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :admin %>
      <%= form.check_box :admin, id: :user_admin %>
    </div>
  </div>
</div>

    <div class="form-group">
      <%= form.button(@user.new_record? ? '<i class="fas fa-user-plus"></i> Create user'.html_safe : '<i class="fas fa-paper-plane"></i> Update profile'.html_safe, class: "btn btn-outline-success btn-sm btn-block") %>
    </div>
    <% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit User</h1>
<div class="row">
	<div class="col-md-6">
		<%= link_to '<i class="fas fa-users"></i> Back to user'.html_safe, @user, 
					class: "btn btn-outline-secondary btn-sm btn-block" %>
		
	</div>
	<div class="col-md-6">
		<%= link_to '<i class="fas fa-eye"></i> Show'.html_safe , @user, 
		                         class: "btn btn-outline-info btn-sm btn-block" %>
	</div>
</div>
	<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1 align="center">Users</h1>
<div class="float-left">
  <%= link_to '<i class="fas fa-caret-left"></i> Back'.html_safe, new_user_path, 
              class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="float-right">
  <%= link_to '<i class="fas fa-user-plus"></i> New user'.html_safe, new_user_path, 
              class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="clearfix"></div>
<br />

<table class="table table-hover">
  <thead class="thead-dark" align="center">
    <tr>
      <th scope="col">Full name</th>      
      <th scope="col">Email</th>      
      <th colspan="3" scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>        
        <td><%= user.email %></td>        
        <td><%= link_to '<i class="fas fa-eye"></i> Show'.html_safe , user, 
                         class: "btn btn-outline-info btn-sm btn-block" %></td>
        <td><%= link_to '<i class="fas fa-user-edit"></i> Edit'.html_safe, edit_user_path(user), 
                         class: "btn btn-outline-primary btn-sm btn-block" %></td>
        <td><%= link_to '<i class="fas fa-user-times"></i> Delete'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm btn-block" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 align="center">New User</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
	<%= render 'form', user: @user %>

	<%= link_to '<i class="fas fa-users"></i> Back to users'.html_safe, users_path, class: "btn btn-outline-secondary btn-sm btn-block" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card" >  
  <div class="card-body">
    <h3 class="card-title text-center"><%= @user.full_name %> </h3>
    <h5 class="card-text text-center"> Start hour <%= @user.start_hour.strftime("%H : %M") %></h5>
    <h4 class="card-text text-center"><% if @user.admin == true %><span class="badge badge-pill badge-secondary">Admin</span><% end %></h4>
    <div class="row">
      <div class="col-md-6">
        <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Email:</strong>  <%= @user.email %></li>
        <li class="list-group-item"><strong>Address:</strong>  <%= @user.address %></li>
        <li class="list-group-item"><strong>D.O.B:</strong>  <%= @user.dob.strftime("%d %b %Y") %></li>
        <li class="list-group-item"><strong>Start Date:</strong>  <%= @user.start_date.strftime("%d %b %Y") %></li>
        <li class="list-group-item"><strong>End Date:</strong><% if @user.end_date == nil %>
        still active <% else %>  <%= @user.end_date.strftime("%d %b %Y") %> <% end %></li>
        <li class="list-group-item"><strong>Position:</strong>  <%= @user.position %></li>
      </ul>
      </div>

      <div class="col-md-6">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Company:</strong>  <%= @user.company.name %></li>
        <li class="list-group-item"><strong>Department:</strong>  <%= @user.department.name %></li>
        </ul>
        <table class="table table-hover">
            <tr>
                <th></th>
                <th scope="col">Entitled</th>
                <th scope="col">Taken</th>
                <th scope="col">Left</th>
            </tr>
            <tr>
                <th scope="row">Holiday</th>
                <td><%= @user.holiday %> days</td>
                <td><%= @user.holiday_taken %> days</td>
                <td><%= (@user.holiday.to_i - @user.holiday_taken.to_i) %> days</td>
            </tr>
            <tr>
                <th scope="row">Sick days</th>
                <td><%= @user.sick_days %> days</td>
                <td><%= @user.sick_days_taken %> days</td>
                <td><%= (@user.sick_days.to_i - @user.sick_days_taken.to_i) %> days</td>
            </tr>
            <tr>
                <th scope="row">Eveniment</th>
                <td><%= @user.eveniment %> days</td>
                <td><%= @user.eveniment_taken %> days</td>
                <td><%= (@user.eveniment.to_i - @user.eveniment_taken.to_i) %> days</td>
            </tr>
        </table>      

        
      </ul>
      </div>
      </div>
      <br>
      <% if current_user.admin? %>
      <div class="row">
        <div class="col-md-6">
        <%= link_to '<i class="fas fa-users"></i> Back to users'.html_safe, users_path, class: "btn btn-outline-secondary btn-sm btn-block" %>
        </div>
        <div class="col-md-6">
        <%= link_to '<i class="fas fa-user-edit"></i> Edit user'.html_safe, edit_user_path(@user), class: "btn btn-outline-primary btn-sm btn-block" %>
        </div>
      </div>
      <% end %>
  </div>
</div>
<br>
<div align="center"><%= mail_to "info@ascheri.co.uk", "Request holiday", :subject => "Holiday request", :body =>"Dear Sir,

I am writing this letter to request you to kindly grant me …(mention duration) holidays from …. to …(mention dates) to attend to personal commitments.
 
I will join back office on ….(mention date).  …(mention reasons for availing leave).

I request you to grant me holidays for ….(duration) and oblige. 

I will brief my team-mate …(name colleague) who will handle my work during my absence. You can contact me on phone at ….. or mail me at …. for any urgent requirement.

Thanking you,

Yours Sincerely,

 

#{@user.full_name}".html_safe, class: "btn btn-outline-primary btn-lg" %></div>
<hr>
<br>


<div class="card" >  
  <div class="card-body">
    <h3 class="card-title text-center">Presence<% if current_user.admin? %><%= link_to '<i class="fas fa-plus"></i> Add'.html_safe, new_presence_path(:user_id => @user), class: "btn btn-outline-primary btn-sm float-right" %><% end %></h3>
    <hr>                      
    <div class="container">
      <div class="row">
        <% @user.presences.order(date: :desc).limit(20).each_slice(5)  do |list| %> 
        <div class="col-md-3">

        <% list.each do |presence| %>
        
          <table class="table table-bordered" align="center" >
          
            <tbody class="float-lest">             
              <tr align="center">
                <th colspan="3" ><%= presence.date.strftime("%d %b %Y") %></th>
              </tr> 
            
              <td align="center"><%= presence.hour_in.strftime("%H : %M") %></td>            
              <td align="center"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_presence_path(presence), class: "btn btn-outline-primary btn-sm" %> | 
              <%= link_to '<i class="fas fa-times"></i>'.html_safe, presence, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td> 
              <tr align="center">              
                <th colspan="3" >
                  <% str1 = presence.hour_in %>
                  <% str2 = @user.start_hour %>                    
                  <% late = (str1.to_i - str2.to_i )  %>
                    <% if late < 0 %>
                      Early <%= (late / -60) %> minutes
                    <% elsif late == 0 %>
                      On time 
                    <% else late > 0 %>
                      Late <%= (late / 60 ) %> minutes
                    <% end %>
                </th>            
              </tr>  
              </tbody>          
                     
            <% end %>
          </table>
          
               
        </div>
      <% end %>
    </div>
  </div>

  </div>
</div>