config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :departments
  resources :companies, only: [:show,:edit, :update]
  resources :users
	root 'sessions#new'
    get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :departments
	has_many :users

	validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @departments = Department.all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <%= render 'shared/errors', obj: @company %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.button '<i class="fas fa-plus"></i> Create Company'.html_safe, class: "btn btn-outline-success btn-sm" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1 align="center">Editing Company</h1>
<div class="float-left">
  <%= link_to '<i class="fas fa-caret-left"></i> Back'.html_safe, @company, 
               class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="clearfix"></div><br>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th> Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1 align="center">New Company</h1>
<div class="float-left">
  <%= link_to '<i class="fas fa-caret-left"></i> Back'.html_safe, companies_path, 
               class: "btn btn-outline-secondary btn-sm" %>
</div>

<div class="clearfix"></div>
<br />

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<h2 align="center"><%= @company.name %></h2>
<div class="float-left">
  <%= link_to '<i class="fas fa-edit"></i> Edit company'.html_safe, edit_company_path(@company), 
              class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="float-right">
  <%= link_to '<i class="fas fa-user-plus"></i> New Deparment'.html_safe, new_department_path(:company_id => @company), 
              class: "btn btn-outline-secondary btn-sm" %>
</div>
<div class="clearfix"></div>
<br />

<table class="table table-hover">
  <thead class="thead-dark" align="center">
    <tr>
      <th scope="col">Department Name</th>
      <th scope="col">Employees No.</th>     
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.users.count  %></td>       
        <td><%= link_to '<i class="fas fa-eye"></i> View Employees'.html_safe, department, 
                        class: "btn btn-outline-info btn-sm btn-block" %></td>
        <td><%= link_to '<i class="fas fa-edit"></i> Edit'.html_safe, edit_department_path(department), class: "btn btn-outline-primary btn-sm btn-block" %></td>
        <td><%= link_to '<i class="fas fa-times"></i> Delete'.html_safe, department, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm btn-block" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>