config/routes.rb
Rails.application.routes.draw do
  resources :presences
  resources :departments
  resources :companies, only: [:show,:edit, :update]
  resources :users
	root 'sessions#new'
    get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- Copyright -->
<footer class="footer">
      <div align="center" class="container footer-bg">
        <span class="text-muted">&copy; Copyright <a href="http://www.ascheri.co.uk">Ascheri & Partners</a></span>
      </div>
    </footer>
<!-- Copyright -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if current_user.admin%>
    <%= link_to "HR Manager", current_user.company, class:"navbar-brand" %></a>
  <%else%>
    <%= link_to "HR Manager", current_user, class:"navbar-brand" %></a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
      <% if current_user.admin%>    
        <%= link_to "Departments", current_user.company, class:"nav-link" %>
      </li>
      <li class="nav-item ">        
        <%= link_to "Employees", users_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
    
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item">
        <%=link_to current_user.first_name, user_path(current_user), class:"nav-link"%>
      </li>      
      <li class="nav-item" >
        <% if (logged_in?) %>
          <%= link_to 'Logout', logout_path, method: :delete, class:"nav-link" %>
        <% end %>
      </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hrmanager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div class="container">
      <% unless controller_name == 'sessions' %> 
        <%= render 'layouts/navbar' %>
      <% end %>
    </div>
  </header>

  <body>
  	<div class="container">
		<div class="msg">
		  <%= render 'shared/messages' %>
		</div>
  	
      <%= yield %>

      
    </div>
  </body>
</html>